/// enum
/// create by marks 2023/05/30

enum ItemType {
  HOLD,
  CANCEL,
}

enum ReportType {
  DAILY_FINANCIAL_REPORT,
  DAILY_FISCAL_CLOUSE,
  ALL,
}

enum CancelType {
  REFUND,
  VOID,
}

enum MessageType {
  ADDITIONAL_HEADER(1),
  TRAILER(2),
  ADDITIONAL_TRAILER(3),
  ADDITIONAL_DESC(4),
  CUSTOMER_ID(7),
  PRINT_OR_ERASE_EFTPOS_TRANS_LINE(8);

  final int value;

  const MessageType(this.value);
}

enum OperationType {
  DISCOUNT_SALE,
  DISCOUNT_DEPARTMENT,
  DISCOUNT_SUBTOTAL_PRINT,
  DISCOUNT_SUBTOTAL_NOT_PRINT,
  SURCHARGE_SALE,
  SURCHARGE_DEPARTMENT,
  SURCHARGE_SUBTOTAL_PRINT,
  SURCHARGE_SUBTOTAL_NOT_PRINT,
  DEPOSIT,
  FREE_OF_CHARGE,
  SINGLE_USE_VOUCHER,
}

enum SubtotalOpt {
  PRINT_DISPLAY,
  PRINT,
  DISPLAY,
}

enum PaymentType {
  CASH,
  CHEQUE,
  CREDIT_OR_CREDIT_CARD,
  TICKET,
  MULTI_TICKET,
  NOT_PAID,
  PAYMENT_DISCOUNT,
}

enum CommandCode {
  OPEN_DRAWER,
  // AUTHORIZESALES,
  // BEGIN_TRAINING,
  // EFTPOS_DAILY_CLOSURE,
  // EFTPOS_GET_CURRENT_TOTAL,
  // END_TRAINING,
  // GET_DATE,
  // PRINT_CONTENT_BY_DATE,
  // PRINT_CONTENT_BY_NUMBERS,
  // PRINT_DUPLICATE_RECEIPT,
  // PRINT_REC_CASH,
  // PRINT_REC_VOID,
  // QUERY_CONTENT_BY_DATE,
  // QUERY_CONTENT_BY_NUMBERS,
  QUERY_PRINTER_STATUS,
  REBOOT_WEB_SERVER,
  RESET_PRINTER,
  // SET_DATE,
  // SET_LOGO,
  GET_NATIVE_CODE_FUNCTION,
  DISPLAY_TEXT,
  PRINT_CONTENT_BY_NUMBERS,
}

// indicates the type of data to collect:
enum DataType {
  ALL,
  COMMERCIAL_DOCS,
  INVOICES,
  BOX_OFFICE_TICKETS,
  OBSOLETE,
}
