name: fiscal_printer
description: Espon fiscal Printer.
version: 0.0.1
homepage: https://github.com/Marks1996/fiscal_printer
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  http: ^0.13.6
  xml: ^6.2.2
  xml2json: ^5.3.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
